name: Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide as much detail as possible.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of KYNEĒ is affected?
      options:
        - Agent (Raspberry Pi)
        - Console Backend
        - Console Frontend
        - Documentation
        - Infrastructure/CI
        - Hardware Integration
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of the bug
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this?
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide version and environment details
      placeholder: |
        - KYNEĒ Version: v0.1.0
        - Hardware: Raspberry Pi 3 Model B+
        - OS: Kali Linux ARM 2024.4
        - Python: 3.11.2
        - Browser (if console): Chrome 120
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Paste relevant logs (redact sensitive info)
      render: shell

  - type: checkboxes
    id: legal
    attributes:
      label: Legal & Ethical Compliance
      description: Confirm this bug was discovered during authorized testing
      options:
        - label: I was conducting authorized testing per signed RoE
          required: true
        - label: I have redacted any sensitive data from this report
          required: true
