name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please ensure it aligns with our [Ethical Use Policy](../../ETHICAL_USE_POLICY.md).

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of KYNEĒ would this affect?
      options:
        - Agent (Raspberry Pi)
        - Console Backend
        - Console Frontend
        - AI Assistant
        - Documentation
        - Infrastructure/CI
        - Hardware Integration
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: As a pentester, I need...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this feature work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches did you consider?

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Describe a specific scenario where this would be useful
      placeholder: During an engagement testing...

  - type: checkboxes
    id: ethical
    attributes:
      label: Ethical Considerations
      description: Confirm this feature complies with our policies
      options:
        - label: This feature is for authorized testing only
          required: true
        - label: This feature includes human-in-the-loop approval (if automated)
          required: false
        - label: This feature does not enable autonomous exploitation
          required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Low (nice to have)
        - Medium (would improve workflow)
        - High (blocks current work)
    validations:
      required: true
